---

sudo: false
dist: xenial

language: python

branches:
  only:
    - master

before_script:
  - pip install tox

script: tox

install: true

notifications:
  email: false

matrix:
  fast_finish: true
  include:

    - python: "2.7"
      env: TOXENV=py27

    - python: "3.6"
      env: TOXENV=py36

    # Linters

    - python: "3.7"
      env: TOXENV=linting
