#!/bin/sh

# Archivematica user creation borrowed from Storage Service postinst
echo "creating archivematica user"
userID=`id -u archivematica`

if [ "${userID}" = 333 ]; then
  echo "User archivematica exists"
else
  adduser --uid 333 --group --system --home /var/lib/archivematica/ archivematica
fi

chgrp archivematica /usr/share/python/fixity/lib/python2.7/site-packages/fixity
chmod g+ws /usr/share/python/fixity/lib/python2.7/site-packages/fixity
