.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "FIXITY" "1" "March 2016" "" ""
.
.SH "NAME"
\fBfixity\fR \- Check fixity for AIPs
.
.SH "SYNOPSIS"
\fBfixity\fR command [options] [UUID]
.
.SH "DESCRIPTION"
fixity is a tool to check fixity of Archival Information Packages (AIPs) stored using the Archivematica Storage Service\.
.
.P
fixity can be configured to POST its reports to a remote service after completing every scan\. It also retains an internal database which keeps track of every AIP it\'s scanned and a report of every scan\.
.
.P
fixity requires several environment variables to be exported when it is running; see the section on \fIENVIRONMENT VARIABLES\fR for information\.
.
.SH "OPTIONS"
.
.TP
\fB\-\-throttle\fR \fIseconds\fR
Time (in seconds) to wait when scanning multiple AIPs\. This can help reduce extended disk load on the filesystem on which the AIPs reside\.
.
.TP
\fB\-\-debug\fR
Print extra debugging output\.
.
.SH "COMMANDS"
.
.TP
\fBscan\fR \fIUUID\fR
Run a fixity scan on a single AIP, using the specified UUID\. If the UUID is malformed, or the Storage Service does not have an AIP with the specified UUID, this will produce an error and exit 1\. After the scan completes, a brief report will be printed with information on whether the scan succeeded or failed\.
.
.TP
\fBscanall\fR
Run a fixity scan on every AIP registered with the target Storage Service instance\. This command does not take any arguments\. A brief report will be printed after every AIP is scanned\.
.
.IP
If \fB\-\-throttle\fR is passed, then the tool will pause for the specified number of seconds between scans\.
.
.SH "ENVIRONMENT VARIABLES"
The following environment variables \fBmust\fR be exported in the environment for fixity to operate\.
.
.TP
\fBSTORAGE_SERVICE_URL\fR
The base URL to the storage service instance to scan\. Must include the port number for non port 80 installations\. Example: http://localhost:8000/
.
.TP
\fBREPORT_URL\fR
The base URL to the remote service to which scan reports will be POSTed\.
.
.TP
\fBREPORT_USERNAME\fR
Username for API authentication with the reporting service\. Not all reporting services require API authentication; leave this unset if API access is unauthenticated\.
.
.TP
\fBREPORT_PASSWORD\fR
Password for API authentication with the reporting service; see above\.

